export default data = [
  
  {
    title: "Piel Canela",
    artist: "Cuco",
    categories: "R&B, Latin, Pop",
    relatedArtists: "Badbunny, Omar Apollo",
    musicLink: require("./cuco.mp3"),
    image:require('./CUCO.png'),
    start: 0,
    end: 15,
  },
  {
    title: "Name",
    artist: "Spill Tab",
    categories: "Bedroom Pop, Pop",
    musicLink: require("./name.mp3"),
    image: require('./spill.jpeg'),
    start: 2,
    end: 17,
  },
  {
    title: "Turtleneck Sweater",
    artist: "Marinelli",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./turtleneckSweater.mp3"),
    image: require('./marinelli.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Someone Else",
    artist: "Deb Never",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./debNever.mp3"),
    image: require('./debNever.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Halloween",
    artist: "Marinelli",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./marinelliHalloween.mp3"),
    image: require('./marinelli.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Halloween",
    artist: "Marinelli",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./marinelliHalloween.mp3"),
    image: require('./marinelli.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Bored & Blind",
    artist: "Ella Jane",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./boredAndBlind.mp3"),
    image: require('./ella.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "nothing else i could do",
    artist: "Ella Jane",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./nothingElse.mp3"),
    image: require('./ella.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "ARIZONA (ft. ella jane)",
    artist: "young friend",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./youngFriend.mp3"),
    image: require('./young-friend.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Boyish",
    artist: "superstar",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./boyish.mp3"),
    image: require('./boyish.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Overdrive",
    artist: "Master Peace",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./Overdrive.mp3"),
    image: require('./masterpeace.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Overdrive",
    artist: "Master Peace",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./winona.mp3"),
    image: require('./winona.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Winona",
    artist: "Miloe",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./winona.mp3"),
    image: require('./winona.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Clueless",
    artist: "Ellie Williams",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./Clueless.mp3"),
    image: require('./eillie.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Apple Pie",
    artist: "Lizzy McAlpine",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./lizzy.mp3"),
    image: require('./lizzy.jpeg'),
    start: 0,
    end: 15,
  },
  {
    title: "Blue",
    artist: "Kamal",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./kamal.mp3"),
    image: require('./kamal.jpg'),
    start: 0,
    end: 15,
  },
  {
    title: "Vintage",
    artist: "Blu DeTiger",
    categories: "Pop, Bedroom Pop",
    musicLink: require("./bluDetiger.mp3"),
    image: require('./bluedetiger.jpeg'),
    start: 0,
    end: 15,
  },
];
